app:
  name: ChatAppBE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ach2
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8082
rabbitmq:
  host: localhost
  virtualhost: /
  username: guest
  password: guest
logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.messaging: DEBUG